config/routes.rb
Rails.application.routes.draw do

   root 'games#index'
   resources :games do
       collection do
           get 'stats'
           post 'start_game'
       end
       member do
           get 'winner'
           get 'hit'
           get 'stand'
       end
   end

end

app/models/card.rb
class Card

  attr_accessor :number, :suit, :value

  def initialize(number, suit, value)
    @number = number
    @suit = suit
    @value = value
  end

  def to_s
    "#{@number} of #{@suit}"
  end
end

app/models/card_deck.rb
class CardDeck 
    attr_reader :deck_of_cards
    def initialize values
        #values = %w{ 11 2 3 4 5 6 7 8 9 10 10 10 10} For blackjack these are values, but other games this could vary.
        @deck_of_cards = []
        ranks = %w{A 2 3 4 5 6 7 8 9 10 J Q K}
        suits = %w{Spades Hearts Diamonds Clubs}
        suits.each do |suit|
          ranks.size.times do |i|
            @deck_of_cards << Card.new( ranks[i], suit, values[i])
          end
        end
    end

    
end

app/models/game.rb
class Game < ActiveRecord::Base
    # State machine for controlling the state of the game
    include AASM
    cattr_accessor :card_stack
    @@num_card_decks = 6
    # Storing the all 6 deck of card objects in this array
    @@card_stack = Array.new(@@num_card_decks , CardDeck.new(%w{ 11 2 3 4 5 6 7 8 9 10 10 10 10}).deck_of_cards).flatten

    serialize :cards_dealt, Array
    has_many :game_steps
    has_one :game_stat

    enum state: {
        started: 0,
        player_move: 1,
        ended: 2
    }
    enum winner: {
        dealer: DEALER,
        player: PLAYER
    }

    aasm :column => :state, :enum => true do
        state :started, :initial => true, :after_enter => :deal_initial_hands
        state :player_move, :after_enter => :greater_than_equal_to_21?
        state :ended

        event :control_to_player do
            transitions :from => [:started], :to => :player_move
        end

        event :end_game do
            transitions :from => [:player_move], :to => :ended, :after => :store_stats
        end

    end


    def self.start_game bet_amt
        game = Game.new.tap do |g|
            g.bet_amount = bet_amt
            g.save
        end
    end

    def hit
        self.cards_dealt << pick_random_card_from_available_cards
        self.save
        self.game_steps.create(move_type: 'hit',cards_dealt_to_player: [self.cards_dealt.last])
        greater_than_equal_to_21?
    end

    def stand
        self.cards_dealt << pick_random_card_from_available_cards
        self.save
        self.game_steps.create(move_type: 'stand',cards_dealt_to_dealer: [self.cards_dealt.last])
        unless greater_than_equal_to_21?
            @dealer_scores = dealer_score
            @player_scores = player_score
            if @dealer_scores <= 16
                stand
            else
                if @player_scores > @dealer_scores
                    self.winner = PLAYER
                elsif @dealer_scores > @player_scores
                    self.winner = DEALER
                end
                end_game!
            end
        end
    end



    def greater_than_equal_to_21?
        puts "player score is #{player_score}, dealer_score is #{dealer_score}"
        @player_scores = player_score
        @dealer_scores = dealer_score
        if @player_scores > 21 || @dealer_scores == 21
            self.winner = DEALER
        elsif @dealer_scores > 21 || @player_scores == 21
            self.winner = PLAYER
        else
            return false
        end
        self.ended_at = Time.now
        end_game!   
        return true
    end

    def player_score
        player_cards.inject(0){|sum,e|
            sum += e.value.to_i}
    end

    def dealer_score
        dealer_cards.inject(0){|sum,e| sum += e.value.to_i}
    end

    def player_cards
        cards_dealt_to_player = []
        self.game_steps.each do |s|
            cards_dealt_to_player.concat s.cards_dealt_to_player
        end
        @player_card_objects = @@card_stack.values_at *cards_dealt_to_player
    end

    def dealer_cards
        cards_dealt_to_dealer = []
        self.game_steps.each do |s|
            cards_dealt_to_dealer.concat s.cards_dealt_to_dealer
        end
        @dealer_card_objects = @@card_stack.values_at *cards_dealt_to_dealer
    end




    def deal_initial_hands
        # Picking three cards randomly to give 2 cards to player and 1 to dealer
        self.cards_dealt << pick_random_card_from_available_cards
        self.cards_dealt << pick_random_card_from_available_cards
        self.cards_dealt << pick_random_card_from_available_cards
        self.save
        self.game_steps.create(move_type: 'deal',cards_dealt_to_player: self.cards_dealt[0..1],cards_dealt_to_dealer: self.cards_dealt[2..2])
        self.control_to_player
    end

    private

    def store_stats
        GameStat.create(player_score: @player_scores,dealer_score: @dealer_scores,game_id: self.id)
    end

    def pick_random_card_from_available_cards
        loop do
            card_stack_index = rand(312)
            unless self.cards_dealt.include? card_stack_index
                return card_stack_index
            end
        end
    end

end

app/models/game_stat.rb
class GameStat < ActiveRecord::Base
    belongs_to :game
end

app/models/game_step.rb
class GameStep < ActiveRecord::Base
    belongs_to :game
    serialize :cards_dealt_to_player, Array
    serialize :cards_dealt_to_dealer, Array
    enum move_type: {
        deal: 0,
        hit: 1,
        stand: 2
    }
    delegate :card_stack, to: :game

    def player_cards_values
        obj = card_stack.values_at *self.cards_dealt_to_player
        obj.map do |c| c.value end
    end

    def dealer_cards_values
        obj = card_stack.values_at *self.cards_dealt_to_dealer
        obj.map do |c| c.value end
    end

    private



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    
    before_action :set_game, only: [:show,:winner,:hit,:stand]
    def index

    end


    def start_game
        @game = Game.start_game(params[:bet_amount] || 100)
        redirect_to @game
    end

    def show
        if @game.player_move?
            @steps = @game.game_steps
        elsif @game.ended?
            redirect_to winner_game_url(@game)
        end
    end

    def hit
        if @game.player_move?
            @game.hit
        end
        redirect_to @game
    end

    def stand
        @game.stand if @game.player_move?
        redirect_to @game
    end

    def stats
        @games = Game.includes(:game_stat).all
        puts @games.inspect
    end

    def winner
        
    end


    private

    def set_game
        @game=Game.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<div class="jumbotron">

    <div class="container">
        <%= form_tag(start_game_games_url,method: "post") do %>
            <div class ="form-group">
                <%= label_tag(:bet_amount, "Bet Amount") %>
                <%= text_field_tag(:bet_amount,nil,class: 'form-control',placeholder: "Default amount is taken as 100" ) %>
            </div>
            <div class ="form-group">
                <%= submit_tag("Start Game",class: "btn btn-primary btn-lg")%>
            </div>
        
        <% end %>
        </div>
    </div>

</div>

app/views/games/show.html.erb
<% @steps.each do |step| %>
    <div class="well"> 
        <h2> Step Type: <%= step.move_type %></h2>
        <h3> Player Cards <span class="label label-success"><%= step.player_cards_values.join('  ') %></span>
            Dealer Cards <span class="label label-danger"><%= step.dealer_cards_values.join('  ') %></span>
        </h3>
    </div>
<% end %>

<%= link_to "Hit",hit_game_path(@game),class: 'btn btn-primary' %>
<%= link_to "Stand",stand_game_path(@game),class: 'btn btn-info' %>

app/views/games/stats.html.erb
<div class="jumbotron">
    <table class="table">
        <th>
            <tr>
                <td>Game No. </td>
                <td>Dealer</td>
                <td>Player </td>
            </tr>
        </th>
        <% if @games.nil? %>
            <tr> <td colspan='3'>No Games Player yet! </td></tr>
        <% else %>
            <% @games.each_with_index do |game,index| %>
                <tbody>

                        <tr>
                            <td> <%= index+1 %></td>
                            <td style="<%= game.winner == 'dealer' ? 'color:green': '' %>"> 
                                <%= game.game_stat.dealer_score %>
                            </td>
                            <td style="<%= game.winner == 'player' ? 'color:green': '' %>">
                                <%= game.game_stat.player_score %>
                            </td>
                        </tr>
                </tbody>
            <% end %>
        <% end %>
    </table>
</div>

app/views/games/winner.html.erb
<div class="jumbotron">
    <div class="well">
        <% if @game.winner %>
             <%= @game.winner.capitalize %> Wins! 
        <% else %>
            Game is drawn!! 
        <% end %>
    </div>
    <div class="well">
        <%= link_to "Deal Again",games_url,class: "btn btn-success" %>
        <%= link_to "Statistics",stats_games_url,class: "btn btn-info" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blackjack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>